export const data = [
    {
        name: 'Chicken Breast',
        calories: 165,
        serving_size_g: 85,
        fat_total_g: 3.5,
        fat_saturated_g: 0.7,
        protein_g: 31,
        sodium_mg: 75,
        potassium_mg: 287,
        cholesterol_mg: 78,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        image_url: 'https://media.istockphoto.com/id/172900971/photo/grilled-chicken.jpg?s=612x612&w=0&k=20&c=crqZAq_4tr_dw4EGng9YvWWFAsh8VzotdETySHFUMzw='
    },
    {
        name: 'Banana',
        calories: 105,
        serving_size_g: 118,
        fat_total_g: 0.4,
        fat_saturated_g: 0.1,
        protein_g: 1.3,
        sodium_mg: 42,
        potassium_mg: 422,
        cholesterol_mg: 0,
        carbohydrates_total_g: 27,
        fiber_g: 3.1,
        sugar_g: 14,
        image_url: 'https://images.everydayhealth.com/images/diet-nutrition/all-about-bananas-nutrition-facts-health-benefits-recipes-and-more-rm-722x406.jpg'
    },
    {
        name: 'Eggs (Scrambled, 2 Eggs)',
        calories: 142,
        serving_size_g: 100,
        fat_total_g: 9,
        fat_saturated_g: 5,
        protein_g: 12,
        sodium_mg: 140,
        potassium_mg: 234,
        cholesterol_mg: 270,
        carbohydrates_total_g: 1,
        fiber_g: 0,
        sugar_g: 1,
        image_url: 'https://cdn.britannica.com/94/151894-050-F72A5317/Brown-eggs.jpg'
    },
    {
        name: 'Oatmeal (Rolled, 1/2 cup, Dry)',
        calories: 150,
        serving_size_g: 50,
        fat_total_g: 3,
        fat_saturated_g: 0.5,
        protein_g: 5,
        sodium_mg: 0,
        potassium_mg: 83,
        cholesterol_mg: 0,
        carbohydrates_total_g: 27,
        fiber_g: 4,
        sugar_g: 1,
        image_url: 'https://images.everydayhealth.com/images/health-benefits-of-oatmeal-1440x810.jpg'
    },
    {
        name: 'Brown Rice (Cooked, 1 cup)',
        calories: 216,
        serving_size_g: 195,
        fat_total_g: 3.5,
        fat_saturated_g: 0.5,
        protein_g: 5,
        sodium_mg: 0,
        potassium_mg: 181,
        cholesterol_mg: 0,
        carbohydrates_total_g: 45,
        fiber_g: 3.5,
        sugar_g: 0.5,
        image_url: 'https://media.istockphoto.com/id/173589620/photo/brown-rice.jpg?s=612x612&w=0&k=20&c=yvu1W2c5fj1Aa6lb-NvWQPXXmL__QWJqS2kGlhCfq0I='
    },
    {
        name: 'Carrot (Raw, 1 large)',
        calories: 52,
        serving_size_g: 128,
        fat_total_g: 0.2,
        fat_saturated_g: 0,
        protein_g: 0.9,
        sodium_mg: 69,
        potassium_mg: 418,
        cholesterol_mg: 0,
        carbohydrates_total_g: 12,
        fiber_g: 3.6,
        sugar_g: 6,
        image_url: 'https://media.licdn.com/dms/image/D4D12AQFkLEP0BaC2RQ/article-cover_image-shrink_720_1280/0/1697298531774?e=2147483647&v=beta&t=Mlu9CcgghlpzTmjofTCQJ1JP4HpSzPHPA9C40F0YsGs'
    },
    {
        name: "brisket",
        calories: 1312.3,
        serving_size_g: 453,
        fat_total_g: 82.9,
        fat_saturated_g: 33.2,
        protein_g: 132,
        sodium_mg: 217,
        potassium_mg: 781,
        cholesterol_mg: 487,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        image_url: 'https://t4.ftcdn.net/jpg/02/36/40/77/360_F_236407792_yLz3WjsXJrZIrmNQMSZOtD9WcgKSLyjA.jpg'

    },
    {
        name: "fries",
        calories: 317.7,
        serving_size_g: 100,
        fat_total_g: 14.8,
        fat_saturated_g: 2.3,
        protein_g: 3.4,
        sodium_mg: 212,
        potassium_mg: 124,
        cholesterol_mg: 0,
        carbohydrates_total_g: 41.1,
        fiber_g: 3.8,
        sugar_g: 0.3,
        image_url: 'https://img.freepik.com/free-photo/crispy-french-fries-with-ketchup-mayonnaise_1150-26588.jpg?size=626&ext=jpg&ga=GA1.1.1700460183.1709596800&semt=ais'

    }

]
